from turtle import *
import turtle as tu

def dibujar_flor(tortuga, x, y):
    tortuga.penup()
    tortuga.goto(x, y)
    tortuga.pendown()

    tortuga.fillcolor("Yellow")
    tortuga.begin_fill()
    tortuga.circle(10, 180)
    tortuga.circle(25, 110)
    tortuga.left(50)
    tortuga.circle(60, 45)
    tortuga.circle(20, 170)
    tortuga.right(24)
    tortuga.fd(30)
    tortuga.left(10)
    tortuga.circle(30, 110)
    tortuga.fd(20)
    tortuga.left(40)
    tortuga.circle(90, 70)
    tortuga.circle(30, 150)
    tortuga.right(30)
    tortuga.fd(15)
    tortuga.circle(80, 90)
    tortuga.left(15)
    tortuga.fd(45)
    tortuga.right(165)
    tortuga.fd(20)
    tortuga.left(155)
    tortuga.circle(150, 80)
    tortuga.left(50)
    tortuga.circle(150, 90)
    tortuga.end_fill()

    tortuga.left(150)
    tortuga.circle(-90, 70)
    tortuga.left(20)
    tortuga.circle(75, 105)
    tortuga.setheading(60)
    tortuga.circle(80, 98)
    tortuga.circle(-90, 40)

    tortuga.left(180)
    tortuga.circle(90, 40)
    tortuga.circle(-80, 98)
    tortuga.setheading(-83)

    tortuga.fd(30)
    tortuga.left(90)
    tortuga.fd(25)
    tortuga.left(45)
    tortuga.fillcolor("dark green")
    tortuga.begin_fill()
    tortuga.circle(-80, 90)
    tortuga.right(90)
    tortuga.circle(-80, 90)
    tortuga.end_fill()
    tortuga.right(135)
    tortuga.fd(60)
    tortuga.left(180)
    tortuga.fd(85)
    tortuga.left(90)
    tortuga.fd(80)

    tortuga.right(90)
    tortuga.right(45)
    tortuga.fillcolor("dark green")
    tortuga.begin_fill()
    tortuga.begin_fill()
    tortuga.circle(80, 90)
    tortuga.left(90)
    tortuga.circle(80, 90)
    tortuga.end_fill()
    tortuga.left(135)
    tortuga.fd(60)
    tortuga.left(180)
    tortuga.fd(60)
    tortuga.right(90)
    tortuga.circle(200, 60)

def main():
    pantalla = tu.Screen()
    pantalla.bgcolor("White")

    tortuga1 = tu.Turtle()
    dibujar_flor(tortuga1, -100, 0)

    tortuga2 = tu.Turtle()
    dibujar_flor(tortuga2, 100, 0)

    texto="ESPERO QUE TE GUSTE, HECHO POR ESTE MAN :D"
    
    tu.penup()
    tu.goto(0, 200)
    tu.pendown()
    tu.write(texto, align="center", font=("Arial", 18, "normal"))

    pantalla.exitonclick()

if __name__ == "__main__":
    main()
